version: '2.2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: aictrobotics/turtlebot3:latest
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      - ros
    # environment:
    #   - "ROS_MASTER_URI=http://ros-master:11311"
    #   - "ROS_HOSTNAME=ros-master"
    # network_mode: "host"
    restart: always

  simulator:
    image: aictrobotics/turtlebot3:latest
    container_name: simulator
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
    #   - "ROS_MASTER_URI=http://ros-master:11311"
    #   - "ROS_HOSTNAME=cam_node"
      - "DISPLAY=unix$DISPLAY"
    # network_mode: "host"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >      
      bash -c "source ~/catkin_ws/devel/setup.bash &&
      export TURTLEBOT3_MODEL=waffle &&
      roslaunch turtlebot3_gazebo turtlebot3_world.launch"
    privileged: true
    restart: always